import { Pool } from "pg";
import { config } from "../config/config";

export const db = new Pool({
  connectionString: config.databaseUrl,
  ssl: config.databaseSsl ? { rejectUnauthorized: false } : undefined,
  max: 5
});

export async function initializeDatabase(): Promise<void> {
  await db.query(`
    CREATE TABLE IF NOT EXISTS games (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      answer TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('active', 'ended')),
      started_at TIMESTAMPTZ NOT NULL,
      ended_at TIMESTAMPTZ,
      max_winners INTEGER NOT NULL CHECK (max_winners > 0)
    );

    CREATE UNIQUE INDEX IF NOT EXISTS idx_games_single_active
      ON games(status)
      WHERE status = 'active';

    CREATE TABLE IF NOT EXISTS participants (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
      user_id TEXT NOT NULL,
      username TEXT NOT NULL,
      total_guesses INTEGER NOT NULL DEFAULT 1,
      first_guess_at TIMESTAMPTZ NOT NULL,
      UNIQUE (game_id, user_id)
    );

    CREATE TABLE IF NOT EXISTS winners (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
      user_id TEXT NOT NULL,
      username TEXT NOT NULL,
      rank INTEGER NOT NULL,
      guessed_at TIMESTAMPTZ NOT NULL,
      UNIQUE (game_id, user_id),
      UNIQUE (game_id, rank)
    );

    CREATE TABLE IF NOT EXISTS guesses (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      game_id BIGINT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
      user_id TEXT NOT NULL,
      username TEXT NOT NULL,
      content TEXT NOT NULL,
      guessed_at TIMESTAMPTZ NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_participants_game_id
      ON participants(game_id);

    CREATE INDEX IF NOT EXISTS idx_winners_game_rank
      ON winners(game_id, rank);

    CREATE INDEX IF NOT EXISTS idx_guesses_game_id
      ON guesses(game_id);

    ALTER TABLE games ENABLE ROW LEVEL SECURITY;
    ALTER TABLE participants ENABLE ROW LEVEL SECURITY;
    ALTER TABLE winners ENABLE ROW LEVEL SECURITY;
    ALTER TABLE guesses ENABLE ROW LEVEL SECURITY;
  `);
}

export async function closeDatabase(): Promise<void> {
  await db.end();
}
